# Generated by Django 4.0.3 on 2022-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_order_orderhandlingfee_alter_order_ordertotalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderPrice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
