# Generated by Django 4.0.3 on 2022-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_events_companycreater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
