# Generated by Django 4.0.3 on 2022-04-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_order_orderprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_avatars',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\DjangoEnv\\NFTTicketPlatform\\media'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatars',
            field=models.ImageField(blank=True, default='imgs/avatar.jpg', null=True, upload_to='C:\\DjangoEnv\\NFTTicketPlatform\\media'),
        ),
    ]
