# Generated by Django 4.0.3 on 2022-03-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_events_eventprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_EndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_StartTime',
            field=models.DateTimeField(null=True),
        ),
    ]
