# Generated by Django 4.0.3 on 2022-04-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_companyprofile_company_avatars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('orderPrice', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('transferFee', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('transferDate_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transferDate_Success', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('UnConfirmed', 'UnConfirmed'), ('Confirmed', 'Confirmed')], default='UnConfirmed', max_length=200, null=True)),
                ('Receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='authentication.customerprofile')),
                ('Sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='authentication.customerprofile')),
                ('senderOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.order')),
                ('tranferEvent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.events')),
            ],
        ),
    ]
