# Generated by Django 4.0.3 on 2022-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_events_date_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_pic',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\DjangoEnv\\NFTTicketPlatform\\media'),
        ),
    ]
