# Generated by Django 4.0.3 on 2022-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_events_event_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Expired', 'Expired')], default='Not Started', max_length=200, null=True),
        ),
    ]
