# Generated by Django 4.0.3 on 2022-04-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_transfer_orderprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='date_created',
        ),
    ]
