# Generated by Django 4.0.3 on 2022-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('Performance', '表演'), ('exhibition', '展覽')], max_length=200, null=True),
        ),
    ]
