# Generated by Django 4.0.3 on 2022-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_events_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('Performance', 'Performance'), ('exhibition', 'exhibition')], max_length=200, null=True),
        ),
    ]
