# Generated by Django 4.0.3 on 2022-04-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_transfer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='receiverNote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='senderNote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
