# Generated by Django 4.0.3 on 2022-04-04 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_transfer_receivernote_transfer_sendernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerorders', to='authentication.customerprofile'),
        ),
    ]
