# Generated by Django 4.0.3 on 2022-04-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_order_tokenid_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('UnConfirmed', 'UnConfirmed'), ('Success', 'Success')], default='UnConfirmed', max_length=200, null=True),
        ),
    ]
