# Generated by Django 4.0.3 on 2022-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatars',
            field=models.ImageField(blank=True, default='avatars/avatar.jpg', null=True, upload_to='C:\\DjangoEnv\\NFTTicketPlatform\\media'),
        ),
    ]
