# Generated by Django 4.0.3 on 2022-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_customerprofile_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='tokenID',
            field=models.IntegerField(default=0),
        ),
    ]
