# Generated by Django 4.0.3 on 2022-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_transfer_tokenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('transferring', 'transferring'), ('UnConfirmed', 'UnConfirmed'), ('Valid', 'Valid'), ('Used', 'Used')], max_length=200, null=True),
        ),
    ]
