# Generated by Django 4.0.3 on 2022-04-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='enterPWD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
